[package]
name = "gemini-bot"
version = "0.2.0"
edition = "2024"

[dependencies]
rig-core = "0.26.0"
serde = "1.0.228"
serde_json = "1.0.145"
serenity = "0.12.4"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
